POST http://localhost:3000/login
Content-Type: application/json 

{
  "username": "christopher_phillips",
  "password": "christy@123"
}

###

GET http://localhost:3000/states 
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.LvenT3Wa6vT7ZhaweKAQqiznr4B3rAeiTfIqUJO2lEE

###

GET http://localhost:3000/states/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.LvenT3Wa6vT7ZhaweKAQqiznr4B3rAeiTfIqUJO2lEE

###

POST http://localhost:3000/districts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.LvenT3Wa6vT7ZhaweKAQqiznr4B3rAeiTfIqUJO2lEE
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

###

GET http://localhost:3000/districts/322
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.LvenT3Wa6vT7ZhaweKAQqiznr4B3rAeiTfIqUJO2lEE

###

DELETE http://localhost:3000/districts/320
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.LvenT3Wa6vT7ZhaweKAQqiznr4B3rAeiTfIqUJO2lEE

###

PUT  http://localhost:3000/districts/333
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.LvenT3Wa6vT7ZhaweKAQqiznr4B3rAeiTfIqUJO2lEE
Content-Type: application/json 

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

###

GET http://localhost:3000/states/3/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Y2hyaXN0b3BoZXJfcGhpbGxpcHM.LvenT3Wa6vT7ZhaweKAQqiznr4B3rAeiTfIqUJO2lEE


###
